Aulas 11 a 20
Julianebf/aulas_laravel pull request #2
Opened 2022-10-11 21:29 UTC by Julianebf

https://www.youtube.com/watch?v=5IL8c2OjzNM&list=PLXik_5Br-zO9xlSwhhEDUGF81M5mgMUFQ&index=11

2022-10-13 14:12 UTC, edmargomes requested changes

2022-10-13 14:12 UTC, edmargomes commented on aulas_laravel/app/Http/Controllers/Main.php
> +    // }
Não enviar codigo comentado

2022-10-13 14:12 UTC, edmargomes commented on aulas_laravel/app/Http/Controllers/Main.php
> +    }
Só para constar, seu TCC é em outro git, aqui é para vc fazer os videos das aulas

2022-10-13 14:12 UTC, edmargomes commented on aulas_laravel/resources/views/user.blade.php
> +</head>
Cade o uso do yield para evitar codigo repitido

2022-10-13 15:09 UTC, Julianebf commented on aulas_laravel/app/Http/Controllers/Main.php
> +    }
mas isso é código dos videos

2022-10-13 16:51 UTC, Julianebf commented on aulas_laravel/resources/views/user.blade.php
> +</head>
nas views ele usa apenas exemplos aleatórios para explicar as rotas, não usa o yield nem templates ainda. eu coloco lá no tcc.

2022-10-15 19:12 UTC, edmargomes approved these changes

2022-10-15 19:12 UTC, merged